apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- range .Values.apiserver.labels }}
    {{.key }}: {{.value }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shibuya
  template:
    metadata:
      labels:
        {{- range .Values.apiserver.labels }}
        {{.key }}: {{.value }}
        {{- end }}
    spec:
      serviceAccount: shibuya
      containers:
      - image: {{ .Values.apiserver.image.name }}:{{ .Values.apiserver.image.tag}}
        name: shibuya
        env:
        {{- range .Values.apiserver.envvars }}
        - name: {{ .key | quote }}
          value: {{ .value | quote }}
        {{- end }}
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: shibuya-config
          mountPath: /config.json
          subPath: config.json
        {{ if eq .Values.runtime.executors.in_cluster false }}
        - name: kubeconfig-volume
          mountPath: /root/.kube/config
          subPath: config
        {{ end }}
      volumes:
      - name: shibuya-config
        configMap:
          name: shibuya-config-{{ .Values.context }}
      {{ if eq .Values.runtime.executors.in_cluster false }}
      - name: kubeconfig-volume
        configMap:
          defaultMode: 420
          name: shibuya-token-{{ .Values.context }}
      {{ end }}

