apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shibuya
  name: shibuya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shibuya
  template:
    metadata:
      labels:
        app: shibuya
    spec:
      serviceAccount: shibuya
      containers:
      - image: {{ .Values.apiserver.image.name }}:{{ .Values.apiserver.image.tag}}
        name: shibuya
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: shibuya-config
          mountPath: /config.json
          subPath: config.json
        {{ if eq .Values.runtime.executors.in_cluster false }}
        - name: kubeconfig-volume
          mountPath: /root/.kube/config
          subPath: config
        {{ end }}
      volumes:
      - name: shibuya-config
        configMap:
          name: shibuya-config-{{ .Values.context }}
      {{ if eq .Values.runtime.executors.in_cluster false }}
      - name: kubeconfig-volume
        configMap:
          defaultMode: 420
          name: shibuya-token-{{ .Values.context }}
      {{ end }}

